import { CAMPAIGN, DIFFICULTIES, DIFFICULTY_NAMES, REGION_THEMES, REWARD_MULT, chapterInfo, stageName, regionStyle } from '../data/campaign';
import { campaign, rating, unlockedChapter, unlockedStage, stageCost, collectedJades, codexBonus, today } from '../systems/campaign';
import { partyPower, type GameSave } from '../systems/adventure';
import { spiritById } from '../data/gameContent';
import { icon, number, portrait, stars, rewardPill, elementBadge } from './components';

export function lanterns(ch:number){const theme=chapterInfo(ch).theme;const coords=theme===2?[[10,11],[19,17],[81,19],[91,11]]:theme===3?[[6,34],[95,34]]:theme===4?[[5,39],[94,39]]:theme===5?[[8,28],[94,28]]:[[6,40],[94,40]];return `<div class="lantern-lights" aria-hidden="true">${coords.map(([x,y],i)=>`<i style="left:${x}%;top:${y}%;--delay:${i*-1.7}s;--lamp:${theme===5?'#8bcbff':'#ffc674'}"></i>`).join('')}</div>`;}
export function campaignPanel(s:GameSave,selected:number,page:number){
 const c=campaign(s),ch=c.chapter,d=c.difficulty,meta=chapterInfo(ch),theme=REGION_THEMES[meta.theme],done=rating(s,ch,selected,d),progress=Array.from({length:20},(_,i)=>rating(s,ch,i+1,d)).filter(Boolean).length,mult=REWARD_MULT[d];
 return `<div class="page-heading"><div><span class="eyebrow">THE SIX BOUNDARIES</span><h1>인연을 따라, 만령로</h1><p>여섯 경계옥을 찾아, 하나로 이어지는 스무 장의 여정.</p></div><button class="outline-button" data-action="world">${icon('explore',17)} 세계 지도</button></div>
 <div class="campaign-controls"><div class="chapter-switch"><button class="icon-button" data-action="chapter" data-id="${ch-1}" ${ch===1?'disabled':''} aria-label="이전 챕터">${icon('back',16)}</button><div><small>CHAPTER ${String(ch).padStart(2,'0')}</small><strong>${meta.title}</strong></div><button class="icon-button" data-action="chapter" data-id="${ch+1}" ${ch>=unlockedChapter(s)?'disabled':''} aria-label="다음 챕터">${icon('chevron',16)}</button></div><div class="filter-tabs difficulty-tabs">${DIFFICULTIES.map((diff,i)=>`<button class="${d===diff?'active':''}" data-action="difficulty" data-id="${diff}" ${i&&!rating(s,ch,20,DIFFICULTIES[i-1])?'disabled':''}>${DIFFICULTY_NAMES[diff]}</button>`).join('')}</div><button class="text-link" data-action="replay-story">${icon('play',14)} 이야기 감상</button></div>
 <section class="adventure-layout"><div class="map-panel" style="${regionStyle(ch)}"><div class="map-art region-art"></div>${lanterns(ch)}<div class="map-vignette"></div><div class="map-heading"><span class="chapter-tag">제 ${ch}장 <i>${DIFFICULTY_NAMES[d]}</i></span><h2>${meta.region}</h2><p>${theme.subtitle}</p></div><div class="map-progress"><span>탐험 진행도</span><strong>${progress}<small> / 20</small></strong><div class="thin-bar"><i style="width:${progress*5}%"></i></div></div><div class="map-route"><svg viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"><path d="M140 335 Q200 320 310 250 T490 325 Q580 360 650 210 T830 150"/></svg>${[[14,67],[31,50],[49,65],[65,42],[83,30]].map(([x,y],i)=>{const st=page*5+i+1,r=rating(s,ch,st,d),open=unlockedStage(s,ch,st,d);return `<button class="map-node ${r?'done':''} ${st===selected?'selected':''} ${!open?'locked':''} ${st%5===0?'boss-node':''}" style="left:${x}%;top:${y}%" data-action="stage" data-id="${st}" aria-label="스테이지 ${ch}-${st} ${stageName(ch,st)} ${r?'완료':!open?'잠김':''}"><span class="node-frame">${r?icon('check',20):icon(!open?'lock':st%5===0?'crown':'explore',20)}</span><b>${ch}-${st}</b>${r?`<small class="stage-stars">${'★'.repeat(r)}${'☆'.repeat(3-r)}</small>`:st===selected?`<small>${stageName(ch,st)}</small>`:''}</button>`;}).join('')}</div><div class="map-bottom"><span class="map-legend">${progress}/20 정화</span><div class="map-pages">${[0,1,2,3].map(i=>`<button class="${page===i?'active':''}" data-action="map-page" data-id="${i}">${i*5+1}–${i*5+5}</button>`).join('')}</div></div></div>
 <aside class="stage-panel panel"><div class="stage-panel-top"><span class="eyebrow">${done?'PURIFIED':'YOUR NEXT STEP'}</span><span class="difficulty">${DIFFICULTY_NAMES[d]}</span></div><span class="stage-number">${ch} — ${String(selected).padStart(2,'0')}</span><h2>${stageName(ch,selected)}</h2><p class="stage-story">${selected===20?`보스 · ${meta.boss}`:meta.intro}</p><div class="divider"></div><div class="stage-info"><span>전투 구성</span><b>${selected===20?'2웨이브 · 보스 2단계':selected===10?'2웨이브 · 중간 보스':'2웨이브 · 4~6기'}</b></div><div class="stage-info"><span>완료 별</span><b class="gold-text">${'★'.repeat(done)}${'☆'.repeat(3-done)}</b></div><div class="stage-rewards">${rewardPill('gold',Math.round((400+selected*80)*(1+(ch-1)*.6)*mult))}${!done?rewardPill('gem',80):''}${rewardPill('equipment',selected%5===0?5:1,'강화석')}</div><p class="drop-note">${selected%5===0?'첫 완료 시 신물 · 혼돈 파편':'생존 5명 + 30라운드 이내 승리 시 3성'}</p><div class="stage-bottom"><button class="primary-button venture" data-action="venture">${icon('explore',18)} ${done?'다시 탐험':'탐험 시작'} ${icon('chevron',17)}</button><div class="stamina-caption">${icon('energy',13)} 행동력 ${stageCost(s,ch,selected,d)} 소모 ${done>=3?'· <button class="text-link" data-action="sweep-options">소탕</button>':''}</div></div></aside></section>
 <section class="party-section"><div class="section-heading"><div><h2>함께하는 요괴 <span>전열 2 · 후열 3</span></h2><p>리더 ${spiritById(c.leader).name} · ${spiritById(c.leader).role==='수호'?'방어':spiritById(c.leader).role==='치유'?'생명':'공격'} +8%</p></div><div class="party-tools"><span>전투력 <b>${number(partyPower(s))}</b></span><button class="outline-button" data-action="formation">편성 변경</button></div></div><div class="party-strip">${s.party.map((id,i)=>{const unit=s.owned.find(u=>u.id===id)!,d=spiritById(id);return `<button class="party-member" data-action="detail" data-id="${id}"><div class="party-portrait">${portrait(id,'',unit.awakening)}</div><div class="party-member-copy"><small>${i<2?'전열':'후열'} · ${d.role}</small><h3>${d.name} ${elementBadge(d.element,true)}</h3>${stars(d.rarity)}<b>Lv. ${unit.level}</b></div></button>`;}).join('')}</div></section>
 <div class="explore-extras"><button class="journey-banner" data-action="daily"><span class="banner-icon">${icon('gift',25)}</span><div><strong>오늘도, 인연을 이어서</strong><small>30일 출석 · 매일 행동력 20 · 소탕권</small></div><span class="text-link">선물 받기</span></button><button class="idle-banner" data-action="offline"><span class="banner-icon">${icon('time',25)}</span><div><strong>정령들의 작은 선물</strong><small>여행을 쉬는 동안 쌓이는 금화</small></div>${icon('chevron',18)}</button></div>`;
}
export function worldPanel(s:GameSave){const c=campaign(s);return `<div class="modal-heading"><span class="eyebrow">THE SIX BOUNDARIES</span><h2>여섯 지역, 스무 장의 이야기</h2><p>평온 난이도에서 챕터 보스를 정화하면 다음 장이 열립니다.</p></div><div class="jade-collection">${['태초석','잠룡옥','등불옥','심연옥','성혼옥','종극옥'].map(j=>`<span class="${collectedJades(s).includes(j)?'collected':''}">◆<small>${j}</small></span>`).join('')}</div><div class="chapter-grid">${CAMPAIGN.map(ch=>`<button data-action="chapter" data-id="${ch.chapter}" ${ch.chapter>unlockedChapter(s)?'disabled':''} class="${c.chapter===ch.chapter?'current':''}"><small>${ch.region} · ${String(ch.chapter).padStart(2,'0')}</small><strong>${ch.title}</strong><span>${rating(s,ch.chapter,20,'쉬움')?'정화 완료':ch.chapter<=unlockedChapter(s)?'탐험 가능':'미개방'}</span></button>`).join('')}</div>${c.ending?'<button class="outline-button full-width" data-action="ending">결말 다시 보기 · 환생</button>':''}`;}
export function dailyPanel(s:GameSave){const c=campaign(s);return `<div class="modal-heading"><span class="eyebrow">ANOTHER DAY TOGETHER</span><h2>하루 한 걸음</h2><p>오늘도 돌아와 준 당신에게, 정령들이 준비한 작은 선물.</p></div><div class="attendance-grid">${Array.from({length:30},(_,i)=>`<div class="${c.attendance>i?'claimed':''} ${[7,14,21,30].includes(i+1)?'milestone':''}"><small>${i+1}일</small>${icon(c.attendance>i?'check':[7,14,21,30].includes(i+1)?'gift':'gem',20)}</div>`).join('')}</div><p>매일 금화 1,000 · 경계석 100 · 소탕권 1<br>7·14·21·30일: 경계석 500, 혼돈 파편 5, 강화석 10 추가</p><button class="primary-button full-width" data-action="attendance" ${c.lastAttendance>=today()?'disabled':''}>${c.lastAttendance>=today()?'오늘 출석 완료':'출석 선물 받기'}</button><button class="outline-button full-width" data-action="daily-stamina" ${c.dailyClaims.includes(today())?'disabled':''}>매일 행동력 20 받기</button><div class="info-box"><p>도감 공명: 전체 능력치 +${(codexBonus(s)*100).toFixed(1)}%</p><p>강화석 ${c.enhanceStones} · 혼돈 파편 ${c.chaos} · 소탕권 ${c.sweepTickets}</p></div>`;}
