import type { GameSave } from '../systems/adventure';
import { partyPower } from '../systems/adventure';
import { DAILY_DUNGEONS, dailyRemaining, dailyTierUnlocked, mazeFloor, mazeRule, challengeRewardText, previewChallengeReward, challengeGate } from '../systems/challenges';
import { regionStyle } from '../data/campaign';
import { icon, number, elementBadge } from './components';
import { pixelSprite } from './pixel';
export function challengePanel(s:GameSave,tier:number){
 const floor=mazeFloor(s),best=s.challenges?.mazeBest??0;
 return `<div class="page-heading"><div><span class="eyebrow">BEYOND THE BOUNDARY</span><h1>경계의 시련</h1><p>인연을 단련하는 네 개의 결계, 그리고 끝을 알 수 없는 길.</p></div><button class="outline-button" data-action="formation">${icon('spirits',18)} 편성 · 전투력 ${number(partyPower(s))}</button></div>
 <section class="trial-intro"><div><span class="eyebrow">DAILY DUNGEONS</span><h2>오늘의 결계</h2><p>각 던전 하루 3회 · 한국 시간 자정 초기화 · 입장 시 행동력 8과 횟수 1 소모</p></div><div class="trial-tiers" aria-label="일일 던전 난이도">${[1,2,3].map(t=>`<button data-action="daily-tier" data-id="${t}" aria-pressed="${t===tier}" ${dailyTierUnlocked(s,t)?'':'disabled'}><b>${t}단계</b><small>${t===1?'기본':t===2?'탐험 10곳 정화':'탐험 30곳 정화'}</small></button>`).join('')}</div></section>
 <div class="daily-dungeon-grid">${DAILY_DUNGEONS.map(d=>{const remaining=dailyRemaining(s,d.id),gate=challengeGate(s,'daily',d.id,tier),reward=previewChallengeReward(s,{kind:'daily',dungeon:d.id,tier,floor:0});return `<article class="daily-dungeon" style="--trial-color:${d.color};${regionStyle(d.chapter)}"><div class="trial-landscape region-art"></div><div class="trial-card-top">${elementBadge(d.element)}<span>오늘 ${remaining} / 3회</span></div><div class="trial-guardian">${pixelSprite(d.boss,'trial-sprite')}<i>${d.mark}</i></div><div class="trial-card-copy"><span class="eyebrow">${d.reward} 수련</span><h3>${d.name}</h3><p>${d.subtitle}</p><div class="trial-rewards">${challengeRewardText(reward)}</div><small class="trial-record">최고 정화 ${s.challenges?.bestTiers[d.id]??0}단계 · 두 번의 전투</small><button class="primary-button" data-action="daily-enter" data-id="${d.id}" ${gate?'disabled':''}>${remaining?'결계에 입장':'오늘의 수련 완료'} ${icon('chevron',16)}</button>${gate&&remaining?`<small class="trial-gate">${gate}</small>`:''}</div></article>`;}).join('')}</div>
 <section class="maze-portal" style="${regionStyle(16)}"><div class="maze-landscape region-art"></div><div class="maze-orbit" aria-hidden="true"><i></i><i></i><span>無<br>窮</span></div><div class="maze-copy"><span class="eyebrow">ENDLESS LABYRINTH</span><h2>끝없는 미궁</h2><p>한 층을 넘을 때마다 강해지는 수호자들.<br>다섯 번째 층에는 결계의 주인이 기다립니다.</p><div class="maze-record"><span>최고 기록 <b>${best}<small>층</small></b></span><span>다음 도전 <b>${floor}<small>층 ${floor%5===0?'· BOSS':''}</small></b></span></div><div class="maze-rule">${mazeRule(floor)}</div><div class="maze-path">${Array.from({length:5},(_,i)=>{const f=floor+i;return `<span class="${f%5===0?'boss-floor':''}">${f%5===0?icon('crown',16):icon('lock',14)} ${f}층</span>`;}).join('')}</div><p class="maze-reward">다음 층 보상 · ${challengeRewardText(previewChallengeReward(s,{kind:'maze',dungeon:'gold',tier:1,floor}))}</p><button class="primary-button" data-action="maze-enter" ${challengeGate(s,'maze')?'disabled':''}>${floor}층에 도전 · 행동력 5 ${icon('chevron',17)}</button><small>층마다 파티를 회복합니다. 패배·후퇴해도 최고 기록은 유지됩니다.</small></div></section>`;
}
