import { GEAR_SLOTS, GEAR_GRADES, RELICS, SLOT_NAMES, STAT_NAMES, spiritById, type EquipSlot } from '../data/gameContent';
import { equipmentInSlot, ownedStats, type GameSave } from '../systems/adventure';
import { campaign } from '../systems/campaign';
import { fullIllustration, illustrationStyle } from './pixel';
import { icon, itemArt, number, portrait, elementBadge } from './components';

export function equipmentPanel(s:GameSave,owner:string,filter:string){
 const u=s.owned.find(u=>u.id===owner)??s.owned[0],d=spiritById(u.id),stats=ownedStats(s,u.id),c=campaign(s);
 const list=s.equipment.filter(e=>(!e.owner||e.owner===u.id)&&(filter==='전체'||RELICS.find(d=>d.id===e.defId)!.slot===filter));
 const illustration=u.id==='gumiho'&&u.awakening<5?`<div class="full-illustration atlas-illustration" role="img" aria-label="구미호 전신 일러스트" style="${illustrationStyle(u.id)}"></div>`:fullIllustration(u.id,u.awakening);
 return `<div class="page-heading"><div><span class="eyebrow">THE SPIRIT ARMORY</span><h1>신물 공방</h1><p>네 가지 신물에, 하나의 인연을 새깁니다.</p></div><button class="outline-button" data-action="craft">${icon('plus',16)} 신물 제작</button></div>
 <div class="armory-roster">${s.owned.map(o=>`<button class="${o.id===u.id?'selected':''}" data-action="gear-owner" data-id="${o.id}" aria-label="${spiritById(o.id).name} 장비 선택">${portrait(o.id,'',o.awakening)}<span>${spiritById(o.id).name}</span></button>`).join('')}</div>
 <section class="armory-layout"><div class="armory-character panel"><div class="armory-name"><span>${d.region} · ${d.role}</span><h2>${d.name} ${elementBadge(d.element,true)}</h2><small>Lv. ${u.level} · 각성 ${u.awakening}</small></div><div class="armory-paperdoll">${illustration}${GEAR_SLOTS.map((slot,i)=>{const e=equipmentInSlot(s,u.id,slot),r=e?RELICS.find(d=>d.id===e.defId)!:null;return `<button class="gear-slot slot-${i} ${filter===slot?'selected':''}" data-action="equip-filter" data-id="${slot}" aria-label="${SLOT_NAMES[slot]} 장비 목록"><small>${SLOT_NAMES[slot]}</small>${r?itemArt(r.art):`<span class="empty-slot">${icon('plus',25)}</span>`}<b>${r?`+${e!.level}`:'미장착'}</b></button>`;}).join('')}</div><div class="armory-stats">${(['atk','def','hp'] as const).map(k=>`<div><small>${STAT_NAMES[k]}</small><b>${number(stats[k])}</b></div>`).join('')}</div><div class="set-progress"><span>${d.element}의 공명 <b>${stats.setCount} / 4</b></span><p class="${stats.setCount>=2?'active':''}">2세트 · 모든 능력치 +12%</p><p class="${stats.setCount===4?'active':''}">4세트 · 모든 능력치 +25%</p></div><div class="button-row"><button class="primary-button" data-action="auto-equip" data-id="${u.id}">추천 장비 장착</button><button class="outline-button" data-action="unequip-all" data-id="${u.id}">전체 해제</button></div></div>
 <div class="armory-inventory"><div class="material-strip"><span>강화석 <b>${number(c.enhanceStones)}</b></span><span>요괴 정수 <b>${number(s.dust)}</b></span><span>신물 <b>${s.equipment.length}</b></span></div><div class="filter-tabs equipment-filters">${['전체',...GEAR_SLOTS].map(k=>`<button class="${filter===k?'active':''}" data-action="equip-filter" data-id="${k}">${k==='전체'?'전체':SLOT_NAMES[k as EquipSlot]}</button>`).join('')}</div><p class="inventory-hint">다른 요괴가 장착한 신물은 해당 요괴를 선택해 해제할 수 있습니다.</p><div class="armory-items">${list.map(e=>{const r=RELICS.find(d=>d.id===e.defId)!,current=equipmentInSlot(s,u.id,r.slot),old=current?RELICS.find(d=>d.id===current.defId)!:null,value=Math.round(r.value*(1+e.level*.15)),delta=value-(old?Math.round(old.value*(1+current!.level*.15)):0);return `<article class="gear-row grade-${r.grade??3}"><button class="gear-icon-button" data-action="item" data-id="${e.uid}" aria-label="${r.name} 강화 정보">${itemArt(r.art)}<b>+${e.level}</b></button><div class="gear-description"><small>${GEAR_GRADES[r.grade??3]} · ${SLOT_NAMES[r.slot]} · ${r.element}</small><h3>${r.name}</h3><p>${STAT_NAMES[r.stat]} +${number(value)} ${e.owner?'':`<em class="${delta>=0?'positive':'negative'}">${delta>=0?'↑ +':'↓ '}${number(delta)}</em>`}</p></div><div class="gear-row-actions"><button class="${e.owner?'outline-button':'primary-button'}" data-action="wear" data-id="${e.uid}">${e.owner?'해제':'장착'}</button><button class="text-link" data-action="item" data-id="${e.uid}">강화 · 제련</button></div></article>`;}).join('')||'<div class="empty-state">이 부위의 신물이 없습니다.<br>탐험 보상이나 공방 제작으로 얻을 수 있습니다.</div>'}</div></div></section>`;
}
export function craftingPanel(){return `<div class="modal-heading"><span class="eyebrow">CRAFT A RELIC</span><h2>오행 신물 제작</h2><p>범상 등급 +0 장비를 만듭니다. 같은 부위·등급의 미장착 +0 장비 3개를 제련하면 다음 등급이 됩니다.</p></div><label class="equip-select-label" for="craft-slot">장비 부위</label><select id="craft-slot">${GEAR_SLOTS.map(k=>`<option value="${k}">${SLOT_NAMES[k]}</option>`).join('')}</select><label class="equip-select-label" for="craft-element">장비 오행</label><select id="craft-element">${['목','화','토','금','수'].map(e=>`<option>${e}</option>`).join('')}</select><button class="primary-button full-width" data-action="craft-confirm">제작 · 금화 600 / 요괴 정수 15</button>`;}

