import { SPIRITS, spiritById } from '../data/gameContent';
import type { GameSave } from '../systems/adventure';
import { campaign } from '../systems/campaign';
import { icon, number, portrait, stars, elementBadge } from './components';
import { generalCounter } from './generalShop';
import { SHOP_LINES } from './shopHost';

export type ShopTab='welcome'|'summon'|'general'|'exchange';
export function summonShop(s:GameSave,tab:ShopTab,unit:string){
 const welcome=tab==='welcome';
 return `<section class="merchant-world room-${tab}" data-shop-room="${tab}" aria-label="인연상회"><div class="merchant-background"></div><div class="merchant-warmth"></div><div class="merchant-steam"><i></i><i></i></div><header class="merchant-top"><button class="merchant-exit" data-action="nav" data-id="explore">${icon('back',16)} 가게 나가기</button><div class="merchant-sign"><small>백귀정 · 달빛 골목</small><h1>인연상회</h1></div><div class="merchant-wallet"><span>${icon('gold',16)} ${number(s.gold)}</span><span>${icon('gem',16)} ${number(s.gems)}</span></div></header>
 <div class="merchant-layout"><aside class="merchant-host"><div class="granny-character" role="img" aria-label="인연 할머니"></div><div class="granny-dialogue"><div><strong>인연 할머니</strong></div><p>${SHOP_LINES[welcome?'welcome':tab==='summon'?'summon':'general']}</p><div class="granny-controls"><button data-action="granny-voice" aria-pressed="true">안내 음성 켜짐</button><button data-action="granny-repeat" aria-label="할머니 목소리 다시 듣기">다시 듣기</button></div><small class="granny-voice-status" role="status">인연상회의 주인</small></div></aside>
 <div class="merchant-content">${welcome?`<div class="merchant-welcome"><span>WELCOME, TRAVELER</span><h2>오늘은 어떤 인연이<br>필요하니?</h2><p>달빛이 머무는 가게, 잠시 쉬어 가세요.</p><div class="merchant-choices"><button data-action="shop-tab" data-id="summon" class="merchant-choice summon-choice"><span class="choice-seal">緣</span><div><small>새로운 동료와의 만남</small><h3>요괴 소환</h3><p>부적 너머, 당신을 기다리는 인연</p></div><b>→</b></button><button data-action="shop-tab" data-id="general" class="merchant-choice general-choice"><span class="choice-seal">品</span><div><small>여정을 위한 작은 준비</small><h3>일반 상점</h3><p>약차 · 소탕권 · 성장 재료 · 정수 교환</p></div><b>→</b></button></div><span class="merchant-hours">등불이 켜져 있는 동안, 언제든 찾아오렴.</span></div>`:`<nav class="merchant-room-nav" aria-label="상점 구역"><button data-action="shop-tab" data-id="welcome">← 할머니에게</button><button data-action="shop-tab" data-id="summon" aria-pressed="${tab==='summon'}">요괴 소환</button><button data-action="shop-tab" data-id="general" aria-pressed="${tab!=='summon'}">일반 상점</button></nav><div class="merchant-room">${tab==='summon'?summonAltar(s):tab==='exchange'?`<div class="exchange-back"><button class="text-link" data-action="shop-tab" data-id="general">← 일반 물품 보기</button></div>${exchangeCounter(s,unit)}`:generalCounter(s)}</div>`}</div></div><footer class="merchant-footer">萬靈路 · 인연은 길 위에, 쉼은 이곳에</footer></section>`;
}
function summonAltar(s:GameSave){
 const pity=s.banner.pullsSinceLastFiveStar;
 return `<div class="shop-banner-heading"><span>달빛 인연 · 픽업 소환</span><button class="text-link" data-action="summon-pool">소환 가능 요괴 ${icon('chevron',13)}</button></div><div class="shop-altar"><div class="altar-halo"><i></i><i></i><b>緣</b></div><div class="altar-motes" aria-hidden="true">${Array.from({length:10},(_,i)=>`<i style="--i:${i};left:${20+i*7}%;top:${25+i*17%50}%"></i>`).join('')}</div><div class="altar-copy"><span>NINE TAILS, ONE DESTINY</span><h2>달 아래 맺은<br><em>아홉 인연</em></h2><p>길을 잃었다면,<br>내 손을 잡아.</p><div>${stars(5)}<h3>${elementBadge('화',true)} 구미호</h3><small>5성 등장 시 픽업 확률 50%</small></div><button class="outline-button" data-action="detail" data-id="gumiho">요괴 살펴보기 ${icon('chevron',13)}</button></div><button class="altar-hero" data-action="detail" data-id="gumiho" aria-label="픽업 구미호 살펴보기">${portrait('gumiho')}<span>九 尾 狐</span></button></div>
 <div class="shop-pity"><div><span>${icon('summon',16)} 다음 5성 확정까지</span><strong>${80-pity}<small>회 이내</small></strong></div><div class="shop-pity-progress"><div class="thin-bar"><i style="width:${pity/80*100}%"></i></div><p><span>현재 ${pity} / 80회</span><b>${s.banner.pickupGuaranteedNext?'다음 5성 구미호 확정':'픽업 실패 시 다음 5성은 구미호'}</b></p></div></div>
 <div class="shop-checkout"><div class="shop-balance"><span>보유 경계석</span><b>${icon('gem',18)} ${number(s.gems)}</b><small>10회 소환 시 300 경계석 절약</small></div><button class="shop-pull single" data-action="pull-review" data-id="1"><span>인연 부르기</span><strong>1회 소환</strong><b>${icon('gem',16)} 300</b></button><button class="shop-pull ten" data-action="pull-review" data-id="10"><span>4성 이상 1종 확정</span><strong>10회 소환</strong><b>${icon('gem',17)} 2,700</b></button></div>`;
}
function exchangeCounter(s:GameSave,unit:string){
 const d=spiritById(unit),u=s.owned.find(u=>u.id===unit)??s.owned[0],c=campaign(s),stone=c.awakeStones[u.id]??0;
 return `<div class="shop-banner-heading"><span>인연을 잇는 정수 교환</span><span>보유 요괴 전용 재료</span></div><div class="exchange-intro"><span>THE EXCHANGE COUNTER</span><h2>다시 만난 인연,<br>더 깊어지는 힘.</h2><p>요괴 정수는 각성석으로, 각성석은 돌파 혼편으로.<br>함께 성장할 요괴를 먼저 골라주세요.</p></div><div class="exchange-owner">${portrait(u.id)}<div><label for="shop-unit">교환 대상</label><select id="shop-unit">${s.owned.map(o=>`<option value="${o.id}" ${o.id===u.id?'selected':''}>${spiritById(o.id).name} · ${o.awakening}각성</option>`).join('')}</select><p>각성석 ${stone} <i>·</i> 혼편 ${u.shards} <i>·</i> 요괴 정수 ${number(s.dust)}</p></div><button class="text-link" data-action="go-awakening" data-id="${u.id}">각성 도감 ${icon('chevron',14)}</button></div><div class="exchange-offers"><article><div class="exchange-gem">${icon('gem',40)}</div><span>AWAKENING STONE</span><h3>${d.name} 각성석</h3><p>전용 각성석 <b>1개</b></p><small>각성에 필요한 전용 재료</small><button class="primary-button" data-action="exchange-awake" data-id="${u.id}" ${s.dust<100?'disabled':''}>요괴 정수 100으로 교환</button>${s.dust<100?'<em>요괴 정수가 부족합니다</em>':''}</article><article><div class="exchange-shard">${icon('spirits',40)}</div><span>SOUL FRAGMENTS</span><h3>${d.name} 혼편</h3><p>돌파 혼편 <b>5개</b></p><small>${d.rarity>=4?'각성과 돌파 중 성장을 선택하세요':'1~3성 혼편은 중복 소환으로 획득합니다'}</small><button class="outline-button" data-action="exchange-shards" data-id="${u.id}" ${stone<1||d.rarity<4?'disabled':''}>전용 각성석 1개로 교환</button>${d.rarity<4?'<em>4~5성 요괴 전용 교환</em>':stone<1?'<em>전용 각성석이 부족합니다</em>':''}</article></div><p class="exchange-note">교환은 선택한 요괴에게 적용됩니다. 각성에는 혼돈 파편과 금화도 필요합니다.</p>`;
}
export function summonReview(s:GameSave,count:number){
 const n=count===10?10:1,price=n===10?2700:300,enough=s.gems>=price;
 return `<div class="shop-review"><span class="eyebrow">MOONLIT SUMMON</span><h2>달빛 인연 · ${n}회 소환</h2><p>${n===10?'4성 이상 요괴 1종을 반드시 만납니다.':'부적 너머에서 새로운 인연을 부릅니다.'}</p><div class="review-talisman">緣</div><dl><div><dt>사용 경계석</dt><dd>${number(price)}</dd></div><div><dt>현재 보유</dt><dd>${number(s.gems)}</dd></div><div><dt>${enough?'소환 후 남는 경계석':'부족한 경계석'}</dt><dd>${number(enough?s.gems-price:price-s.gems)}</dd></div></dl><p class="review-guarantee">5성 확정까지 ${80-s.banner.pullsSinceLastFiveStar}회 이내<br>${s.banner.pickupGuaranteedNext?'다음 5성은 구미호 확정':'5성 출현 시 구미호 50% · 픽업 실패 시 다음 5성 픽업 확정'}</p><button class="primary-button full-width" data-action="${enough?'pull':'quests'}" data-id="${n}">${enough?'소환 시작':'경계석을 얻을 임무 보기'}</button><button class="text-link" data-action="close">상점으로 돌아가기</button></div>`;
}
export function summonPool(){
 return `<div class="pool-heading"><span class="eyebrow">SUMMONING POOL</span><h2>이곳에서 만나는 인연</h2><p>총 ${SPIRITS.filter(d=>!d.storyOnly).length}종 · 스토리 동료는 챕터 보상으로 합류합니다.</p></div><div class="shop-pool">${[5,4,3,2,1].map(n=>`<section><h3>${stars(n)} <small>${SPIRITS.filter(d=>d.rarity===n&&!d.storyOnly).length}종</small></h3><div>${SPIRITS.filter(d=>d.rarity===n&&!d.storyOnly).map(d=>`<button data-action="detail" data-id="${d.id}">${portrait(d)}<span>${d.name}</span>${d.id==='gumiho'?'<small>PICK UP</small>':''}</button>`).join('')}</div></section>`).join('')}</div><button class="outline-button full-width" data-action="rates">등급별 확률 보기</button>`;
}
