import './ui/style.css';
import './ui/pixel.css';
import './ui/expansion.css';
import './ui/collectionShop.css';
import './ui/storyLibrary.css';
import './ui/livingWorld.css';
import './ui/journeyPolish.css';
import './ui/combatChoreography.css';
import './ui/expeditions.css';
import { startGame } from './ui/game';
startGame();
